version: '3.1'

services:
  db:
    image: postgres:11.5
    restart: always
    container_name: "my_postgres"
    expose:
      - 5432
    env_file: database.conf
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    depends_on:
      - redis
  redis:
    image: redis:5.0-alpine
    container_name: "my_redis"
    expose:
      - "6379"
    ports:
      - "6378:6379"
  web:
    build: .
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - redis
      - db

