version: '3.7'

services:
  db_service:
    image: postgres:11.5
    restart: always
    container_name: "myPostgres"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test12345
      - POSTGRES_PORT=5432
      - POSTGRES_DB=personal_website
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    depends_on:
      - redis_service
  redis_service:
    image: redis:5.0-alpine
    container_name: "myRedis"
    expose:
      - 6379
    entrypoint: redis-server
    ports:
      - "6378:6379"
  web_service:
    build: .
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - redis_service
      - db_service

